language: python
python:
- 3.6
service: docker
git:
  depth: false
  quiet: true
notifications:
  email:
  recipients:
  - tomas.forne-cappeau@epitech.eu
  on_success: never
  on_failure: always
jobs:
  include:
  - stage: Build
    name: Building image
    script: make build
  - stage: Tests
    name: Adding files
    script:
    - make
    - chmod +x ./ci/test_add.sh
    - "./ci/test_add.sh"
  - name: Removing files
    script:
    - make
    - chmod +x ./ci/test_remove.sh
    - "./ci/test_remove.sh"
  - name: Moving files
    script:
    - make
    - chmod +x ./ci/test_remove.sh
    - "./ci/test_move.sh"
  - name: All tests with the same environment
    script:
    - make tests_run
  - stage: Deployment
    name: Push to docker hub
    script:
    - docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
    - docker build . -t colcolt/makefile_completer:latest
    - "./ci/deploy/deploy.sh"
stages:
- Build
- Tests
- name: Deployment
  if: branch IN (master) AND type != cron AND type != pull_request
env:
  global:
  - secure: R3matETpoZYCc+V4+6EoNG0cM+FJdljziA2sK1p9boY2jRR6GhK7b+rxgu6MseDpzqCvEj4CMoIkRTLRfEwFiBU7oDnjDb1tPJ+RKR61HiqdInHpX952bs6bgxLIF3cyygao9dugEhkopxucip5Jn6lXtl7Uizks5n0APx1n0LR7iYk9rRUcWqyfABRWXv8y8roV0RKOVcesD2A39jg7bu4EiEHPUKvHoeFrJDdAvTEqhFmtYcfakrPXqd/bJevoroG3mZuY/PDAGT2MCoqZAHe2Lc88a0EFyXcQ+8ode8466GunECKJGcLHsuFzl3q3zqIe7RzGZ4GTcDcm1M9VXDQ0p9tTtEAKzgEusiXbcz+X+ms2o6s5vimqC8XEntf0p/leNZvSfx4P60d3ESNri8eWf+9E2lmLvpj/apDQphkx/6D99srE0xNHIMXSlwmyLAPdrnwk9tUPWHxny1ruYv/y1nUcKuYulpm8mRWAAEGj+iVLRMGs6AsaQ9/ZMfvAuQK9Qf0bxGBFG8HkF4P36Hwo6LkoUJ9WmO+lwbGw7fAJWsGPwPZbx/NGdlUVTvNo8FBNG1Vbak4Wd54th0YqTw/qMz+m4jV8wm2QDH2r/fajqhDsS4o0iEuL/qKaZCbeTYihM9oUsJBjntGMzhdNtnlRRKHWJWt+eGF9GTtWKZw=
  - secure: mVnFJjmMb4M4Vh+UXbseJKHlh8H1FAxT77cbQx+5R8o1IgZqB4ze5WmkcGjdQMy6MYncu8XKjYeuvY/W0pVb5j+n/5yPZeU8BIytpKnMKb5xu4gtRx+m4WjfV7R4jT8ec7THQ2O3M+YbG7vJ9bszXGT7y1KCRGI7/5G6ZgNH/ku7JOz61r2DPbX6lqNaSu3qX3wdOziTtm5X7pgvy2prM2wnyuSiEgO5Z9Dnqvk1YR6DrkSyamB9J99lsMLfes6dzKGYfO2e1pju13SyZOhdV+ULyfa8VTJ+wM9AXSVJRjOT7M9JyReDlRjDHdCXqHkHO0kvZaSBIPITYOHg87Zil6m5mWGYyVGMviAAwsrI2ba5wNsOkUbuk3d8uflZGFL7VuISaaOD451uXJCj/f5SI7lv8c1h/q/Wkhu4J0NzAwg+FB2s8/qcyGVLoU6mP2V7TYn2XB21mMnmTH/rRoM718squlvkKfWwBNCAE0OiKMrF6b6ly6pvjLDhEGsct1F4037LV2ip/5UxI19FovBUaNtbzSC1hgZYTKjw56fuYCYxVJrBbTjhTw7us+HdrG50br3Lsj9p2d94dwyJwkjzn+qa5lf3VaGkv7qFzXOD5QJcoXDQHfncnW70gwZHswPL/c15pVKdsPpp9rZp1OAqKQ1RjXBBVNxkBq4R5qpDKZY=
